export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS_REGISTER = "AUTH_SUCCESS_REGISTER";
export const AUTH_SUCCESS_LOGIN = "AUTH_SUCCESS_LOGIN";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_TYPE = "AUTH_TYPE";